skylines/__init__.py
# flake8: noqa

from skylines.app import (
    create_app,
    create_http_app,
    create_frontend_app,
    create_api_app,
    create_combined_app,
    create_celery_app,
)

from skylines.__about__ import (
    __title__, __summary__, __uri__, __version__, __author__, __email__,
    __license__,
)

skylines/api/views/__init__.py
from flask import request
from werkzeug.exceptions import Forbidden
from werkzeug.useragents import UserAgent

from skylines.api.cors import cors

from skylines.api.views.about import about_blueprint
from skylines.api.views.airports import airports_blueprint
from skylines.api.views.aircraft_models import aircraft_models_blueprint
from skylines.api.views.clubs import clubs_blueprint
from skylines.api.views.flights import flights_blueprint
from skylines.api.views.i18n import i18n_blueprint
from skylines.api.views.mapitems import mapitems_blueprint
from skylines.api.views.notifications import notifications_blueprint
from skylines.api.views.ranking import ranking_blueprint
from skylines.api.views.search import search_blueprint
from skylines.api.views.settings import settings_blueprint
from skylines.api.views.statistics import statistics_blueprint
from skylines.api.views.timeline import timeline_blueprint
from skylines.api.views.tracking import tracking_blueprint
from skylines.api.views.upload import upload_blueprint
from skylines.api.views.users import users_blueprint


def register(app):
    """
    :param flask.Flask app: a Flask app
    """

    from .errors import register as register_error_handlers

    @app.before_request
    def require_user_agent():
        """
        API requests require a ``User-Agent`` header
        """
        user_agent = request.user_agent
        assert isinstance(user_agent, UserAgent)

        if not user_agent.string:
            description = 'You don\'t have the permission to access the API with a User-Agent header.'
            raise Forbidden(description)

    cors.init_app(app)

    register_error_handlers(app)

    app.register_blueprint(about_blueprint)
    app.register_blueprint(airports_blueprint)
    app.register_blueprint(aircraft_models_blueprint)
    app.register_blueprint(clubs_blueprint)
    app.register_blueprint(flights_blueprint)
    app.register_blueprint(i18n_blueprint)
    app.register_blueprint(mapitems_blueprint)
    app.register_blueprint(notifications_blueprint)
    app.register_blueprint(ranking_blueprint)
    app.register_blueprint(search_blueprint)
    app.register_blueprint(settings_blueprint)
    app.register_blueprint(statistics_blueprint)
    app.register_blueprint(timeline_blueprint)
    app.register_blueprint(tracking_blueprint)
    app.register_blueprint(upload_blueprint)
    app.register_blueprint(users_blueprint)

skylines/api/views/about.py
import os.path

from flask import Blueprint, current_app

from skylines.api.json import jsonify

about_blueprint = Blueprint('about', 'skylines')


@about_blueprint.route('/imprint')
def imprint():
    content = current_app.config.get(
        'SKYLINES_IMPRINT',
        'Please set the `SKYLINES_IMPRINT` variable in the config file.')

    return jsonify(content=content)


@about_blueprint.route('/team')
def skylines_team():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', '..', '..', 'AUTHORS.md')
    with open(path) as f:
        content = f.read().decode('utf-8')

    return jsonify(content=content)


@about_blueprint.route('/license')
def license():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', '..', '..', 'LICENSE')
    with open(path) as f:
        content = f.read().decode('utf-8')

    return jsonify(content=content)

skylines/api/views/aircraft_models.py
from flask import Blueprint

from skylines.api.json import jsonify
from skylines.model import AircraftModel
from skylines.schemas import AircraftModelSchema

aircraft_models_blueprint = Blueprint('aircraft_models', 'skylines')


@aircraft_models_blueprint.route('/aircraft-models', strict_slashes=False)
def index():
    models = AircraftModel.query() \
        .order_by(AircraftModel.kind) \
        .order_by(AircraftModel.name) \
        .all()

    return jsonify(models=AircraftModelSchema().dump(models, many=True).data)

skylines/api/views/airports.py
from flask import Blueprint

from skylines.api.json import jsonify
from skylines.lib.dbutil import get_requested_record
from skylines.model import Airport
from skylines.schemas import AirportSchema

airports_blueprint = Blueprint('airports', 'skylines')


@airports_blueprint.route('/airports/<int:airport_id>')
def index(airport_id):
    airport = get_requested_record(Airport, airport_id)
    return jsonify(AirportSchema().dump(airport).data)

skylines/api/views/clubs.py
from flask import Blueprint, request
from sqlalchemy import func

from skylines.api.json import jsonify
from skylines.database import db
from skylines.api.oauth import oauth
from skylines.lib.dbutil import get_requested_record
from skylines.model import Club, User
from skylines.model.event import (
    create_club_join_event
)

from skylines.schemas import ClubSchema, ValidationError

clubs_blueprint = Blueprint('clubs', 'skylines')


@clubs_blueprint.route('/clubs', strict_slashes=False)
def list():
    clubs = Club.query().order_by(func.lower(Club.name))

    name_filter = request.args.get('name')
    if name_filter:
        clubs = clubs.filter_by(name=name_filter)

    return jsonify(clubs=ClubSchema(only=('id', 'name')).dump(clubs, many=True).data)


@clubs_blueprint.route('/clubs/<club_id>', strict_slashes=False)
@oauth.optional()
def read(club_id):
    current_user = User.get(request.user_id) if request.user_id else None

    club = get_requested_record(Club, club_id)

    json = ClubSchema().dump(club).data
    json['isWritable'] = club.is_writable(current_user) or False

    return jsonify(json)


@clubs_blueprint.route('/clubs', methods=['PUT'])
@oauth.required()
def create_club():
    current_user = User.get(request.user_id)
    if not current_user:
        return jsonify(error='invalid-token'), 401

    json = request.get_json()
    if json is None:
        return jsonify(error='invalid-request'), 400

    try:
        data = ClubSchema(only=('name',)).load(json).data
    except ValidationError, e:
        return jsonify(error='validation-failed', fields=e.messages), 422

    if Club.exists(name=data.get('name')):
        return jsonify(error='duplicate-club-name'), 422

    # create the new club
    club = Club(**data)
    club.owner_id = current_user.id
    db.session.add(club)
    db.session.flush()

    # assign the user to the new club
    current_user.club = club

    # create the "user joined club" event
    create_club_join_event(club.id, current_user)

    db.session.commit()

    return jsonify(id=club.id)


@clubs_blueprint.route('/clubs/<club_id>', methods=['POST'], strict_slashes=False)
@oauth.required()
def update(club_id):
    current_user = User.get(request.user_id)
    if not current_user:
        return jsonify(error='invalid-token'), 401

    club = get_requested_record(Club, club_id)
    if not club.is_writable(current_user):
        return jsonify(error='forbidden'), 403

    json = request.get_json()
    if json is None:
        return jsonify(error='invalid-request'), 400

    try:
        data = ClubSchema(partial=True).load(json).data
    except ValidationError, e:
        return jsonify(error='validation-failed', fields=e.messages), 422

    if 'name' in data:
        name = data.get('name')

        if name != club.name and Club.exists(name=name):
            return jsonify(error='duplicate-club-name'), 422

        club.name = name

    if 'website' in data:
        club.website = data.get('website')

    db.session.commit()

    return jsonify()

skylines/api/views/flights.py
import math
from datetime import datetime, timedelta

from flask import Blueprint, request, abort, current_app, make_response

from sqlalchemy import func, literal_column
from sqlalchemy.sql.expression import or_, and_
from sqlalchemy.orm import joinedload, contains_eager, undefer_group
from sqlalchemy.orm.util import aliased
from geoalchemy2.shape import to_shape
from redis.exceptions import ConnectionError

from skylines.api.json import jsonify
from skylines.database import db
from skylines.api.cache import cache
from skylines.api.oauth import oauth
from skylines.lib import files
from skylines.lib.table_tools import Pager, Sorter
from skylines.lib.dbutil import get_requested_record
from skylines.lib.xcsoar_ import analyse_flight
from skylines.lib.datetime import from_seconds_of_day
from skylines.lib.geo import METERS_PER_DEGREE
from skylines.lib.geoid import egm96_height
from skylines.model import (
    User, Club, Flight, IGCFile, AircraftModel,
    Airport, FlightComment,
    Notification, Event,
    Elevation, Location, FlightMeetings,
)
from skylines.model.event import create_flight_comment_notifications
from skylines.schemas import (
    fields, FlightSchema, FlightCommentSchema, FlightPhaseSchema, ContestLegSchema,
    AircraftModelSchema, AirportSchema, ClubSchema, UserSchema, Schema, ValidationError
)
from skylines.worker import tasks

import xcsoar

flights_blueprint = Blueprint('flights', 'skylines')


def mark_user_notifications_read(pilot):
    if not request.user_id:
        return

    def add_flight_filter(query):
        return query.filter(Event.actor_id == pilot.id)

    Notification.mark_all_read(User.get(request.user_id), filter_func=add_flight_filter)
    db.session.commit()


def _create_list(date=None, pilot=None, club=None, airport=None,
                 pinned=None, filter=None,
                 default_sorting_column='score', default_sorting_order='desc'):

    pilot_alias = aliased(User, name='pilot')
    owner_alias = aliased(User, name='owner')

    subq = db.session \
        .query(FlightComment.flight_id, func.count('*').label('count')) \
        .group_by(FlightComment.flight_id).subquery()

    current_user = User.get(request.user_id) if request.user_id else None

    flights = db.session.query(Flight, subq.c.count) \
        .filter(Flight.is_listable(current_user)) \
        .join(Flight.igc_file) \
        .options(contains_eager(Flight.igc_file)) \
        .join(owner_alias, IGCFile.owner) \
        .options(contains_eager(Flight.igc_file, IGCFile.owner, alias=owner_alias)) \
        .outerjoin(pilot_alias, Flight.pilot) \
        .options(contains_eager(Flight.pilot, alias=pilot_alias)) \
        .options(joinedload(Flight.co_pilot)) \
        .outerjoin(Flight.club) \
        .options(contains_eager(Flight.club)) \
        .outerjoin(Flight.takeoff_airport) \
        .options(contains_eager(Flight.takeoff_airport)) \
        .outerjoin(Flight.model) \
        .options(contains_eager(Flight.model)) \
        .outerjoin((subq, Flight.comments))

    if date:
        flights = flights.filter(Flight.date_local == date)

    if pilot:
        flights = flights.filter(or_(Flight.pilot == pilot,
                                     Flight.co_pilot == pilot))
    if club:
        flights = flights.filter(Flight.club == club)

    if airport:
        flights = flights.filter(Flight.takeoff_airport == airport)

    if pinned:
        flights = flights.filter(Flight.id.in_(pinned))

    if filter is not None:
        flights = flights.filter(filter)

    valid_columns = {
        'date': getattr(Flight, 'date_local'),
        'score': getattr(Flight, 'index_score'),
        'pilot': getattr(pilot_alias, 'name'),
        'distance': getattr(Flight, 'olc_classic_distance'),
        'airport': getattr(Airport, 'name'),
        'club': getattr(Club, 'name'),
        'aircraft': getattr(AircraftModel, 'name'),
        'time': getattr(Flight, 'takeoff_time'),
    }

    flights_count = flights.count()

    flights = Sorter.sort(flights, 'flights', default_sorting_column,
                          valid_columns=valid_columns,
                          default_order=default_sorting_order)

    flights = flights.order_by(Flight.index_score.desc())

    flights = Pager.paginate(flights, 'flights',
                             items_per_page=int(current_app.config.get('SKYLINES_LISTS_DISPLAY_LENGTH', 50)))

    flight_schema = FlightSchema()
    flights_json = []
    for f, num_comments in flights:
        flight = flight_schema.dump(f).data
        flight['private'] = not f.is_rankable()
        flight['numComments'] = num_comments
        flights_json.append(flight)

    json = dict(flights=flights_json, count=flights_count)

    if date:
        json['date'] = date.isoformat()

    if pilot:
        user_schema = UserSchema(only=('id', 'name'))
        json['pilot'] = user_schema.dump(pilot).data

    if club:
        club_schema = ClubSchema(only=('id', 'name'))
        json['club'] = club_schema.dump(club).data

    if airport:
        airport_schema = AirportSchema(only=('id', 'name', 'countryCode'))
        json['airport'] = airport_schema.dump(airport).data

    return jsonify(json)


@flights_blueprint.route('/flights/all')
@oauth.optional()
def all():
    return _create_list(default_sorting_column='date', default_sorting_order='desc')


@flights_blueprint.route('/flights/date/<date>')
@oauth.optional()
def date(date, latest=False):
    try:
        if isinstance(date, (str, unicode)):
            date = datetime.strptime(date, "%Y-%m-%d")

        if isinstance(date, datetime):
            date = date.date()

    except:
        return jsonify(), 404

    return _create_list(date=date, default_sorting_column='score', default_sorting_order='desc')


@flights_blueprint.route('/flights/latest')
@oauth.optional()
def latest():
    current_user = User.get(request.user_id) if request.user_id else None

    query = db.session \
        .query(func.max(Flight.date_local).label('date')) \
        .filter(Flight.takeoff_time < datetime.utcnow()) \
        .join(Flight.igc_file) \
        .filter(Flight.is_listable(current_user))

    date_ = query.one().date
    if not date_:
        date_ = datetime.utcnow()

    return date(date_, latest=True)


@flights_blueprint.route('/flights/pilot/<int:id>')
@oauth.optional()
def pilot(id):
    pilot = get_requested_record(User, id)

    mark_user_notifications_read(pilot)

    return _create_list(pilot=pilot, default_sorting_column='date', default_sorting_order='desc')


@flights_blueprint.route('/flights/club/<int:id>')
@oauth.optional()
def club(id):
    club = get_requested_record(Club, id)

    return _create_list(club=club, default_sorting_column='date', default_sorting_order='desc')


@flights_blueprint.route('/flights/airport/<int:id>')
@oauth.optional()
def airport(id):
    airport = get_requested_record(Airport, id)

    return _create_list(airport=airport, default_sorting_column='date', default_sorting_order='desc')


@flights_blueprint.route('/flights/unassigned')
@oauth.required()
def unassigned():
    f = and_(Flight.pilot_id is None, IGCFile.owner_id == request.user_id)

    return _create_list(filter=f, default_sorting_column='date', default_sorting_order='desc')


@flights_blueprint.route('/flights/list/<ids>')
@oauth.optional()
def list(ids):
    if not ids:
        return jsonify(), 400

    try:
        # Split the string into integer IDs
        ids = [int(id) for id in ids.split(',')]
    except ValueError:
        return jsonify(), 404

    return _create_list(pinned=ids, default_sorting_column='date', default_sorting_order='desc')


def _reanalyse_if_needed(flight):
    if flight.needs_analysis:
        current_app.logger.info("Queueing flight %s for reanalysis" % flight.id)
        try:
            tasks.analyse_flight.delay(flight.id)
        except ConnectionError:
            current_app.logger.info('Cannot connect to Redis server')
            # analyse syncronously...
            analyse_flight(flight)
            db.session.commit()


def _patch_query(q):
    current_user = User.get(request.user_id) if request.user_id else None

    return q.join(Flight.igc_file) \
        .options(contains_eager(Flight.igc_file)) \
        .filter(Flight.is_viewable(current_user))


def _get_flight_path(flight, threshold=0.001, max_points=3000):
    num_levels = 4
    zoom_factor = 4
    zoom_levels = [0]
    zoom_levels.extend([round(-math.log(32.0 / 45.0 * (threshold * pow(zoom_factor, num_levels - i - 1)), 2)) for i in range(1, num_levels)])

    xcsoar_flight = xcsoar.Flight(files.filename_to_path(flight.igc_file.filename))

    if flight.qnh:
        xcsoar_flight.setQNH(flight.qnh)

    begin = flight.takeoff_time - timedelta(seconds=2 * 60)
    end = flight.landing_time + timedelta(seconds=2 * 60)

    if begin > end:
        begin = datetime.min
        end = datetime.max

    xcsoar_flight.reduce(begin=begin,
                         end=end,
                         num_levels=num_levels,
                         zoom_factor=zoom_factor,
                         threshold=threshold,
                         max_points=max_points)

    encoded_flight = xcsoar_flight.encode()

    points = encoded_flight['locations']
    barogram_t = encoded_flight['times']
    barogram_h = encoded_flight['altitude']
    enl = encoded_flight['enl']

    elevations_t, elevations_h = _get_elevations(flight)
    contest_traces = _get_contest_traces(flight)

    geoid_height = egm96_height(flight.takeoff_location) if flight.takeoff_location else 0

    return dict(points=points,
                barogram_t=barogram_t, barogram_h=barogram_h,
                enl=enl, contests=contest_traces,
                elevations_t=elevations_t, elevations_h=elevations_h,
                sfid=flight.id, geoid=geoid_height)


def _get_elevations(flight):
    elevations = get_elevations_for_flight(flight)

    # Encode lists

skylines/templates/notifications/notifications-table.jinja
{% from "macros/datetime.jinja" import insert_timeago with context %}
{% from "macros/links.jinja" import user_link %}


{% macro render_events_table(events) -%}
<table class="table table-events">
  <tbody>
    {% for event in events -%}
    {{ render_event_row(event) }}
    {%- endfor %}
  </tbody>
</table>
{%- endmacro %}


{% macro render_event_row(event) -%}
<tr>
  <td class="icon">
    {{ render_event_icon(event) }}
  </td>
  <td>
    <p>
      {% if event.unread %}<span class="badge badge-warning">{{ _('New') }}</span>{% endif %}
      <small>{{ insert_timeago(event.time) }}</small>
    </p>
    <p>
    {{ render_event_text(event) }}
    </p>
    <p>
    {% if event.grouped -%}
      {% for event in event.subevents -%}
        <small>
          {% if event.unread %}<span class="badge badge-warning badge-empty"></span>{% endif %}
          {{ render_event_text(event) }}
          <a href="{{ event_link(event) }}"><i class="icon-circle-arrow-right"></i></a>
        </small>
        <br/>
      {%- endfor %}
    {%- endif %}
    </p>
  </td>
  <td class="show">
    {{ _render_show_button(event_link(event)) }}
  </td>
</tr>
{%- endmacro %}


{% macro render_event_icon(event) -%}
{% if event.type == types.FLIGHT_COMMENT -%}
  <i class="icon-comments-alt"></i>
{%- elif event.type == types.FLIGHT %}
  <i class="icon-plane"></i>
{%- elif event.type == types.FOLLOWER %}
  <i class="icon-user"></i>
{%- endif %}&nbsp;
{%- endmacro %}


{% macro render_event_text(event) -%}
{% if event.grouped -%}
  {% if event.type == types.FLIGHT -%}
    {{ render_grouped_flights_event_text(event) }}
  {%- elif event.type == types.FOLLOWER -%}
    {{ render_grouped_followers_event_text(event) }}
  {%- else %}
    Error: Unknown event group
  {%- endif %}
{%- else %}
  {% if event.type == types.FLIGHT_COMMENT -%}
    {{ render_flight_comment_event_text(event) }}
  {%- elif event.type == types.FLIGHT %}
    {{ render_flight_event_text(event) }}
  {%- elif event.type == types.FOLLOWER %}
    {{ render_follower_event_text(event) }}
  {%- else %}
    Error: Unknown event
  {%- endif %}
{%- endif %}
{%- endmacro %}


{% macro render_flight_comment_event_text(event) -%}
{% if g.current_user and (event.flight.pilot_id == current_user.id or event.flight.co_pilot_id == current_user.id) -%}
  {{ _('<strong>%(pilot)s</strong> commented on your <strong>%(distance)s</strong> flight on the <strong>%(date)s</strong>.',
       pilot=user_link(event.actor),
       distance=h.format_distance(event.flight.olc_classic_distance),
       date=h.format_date(event.flight.date_local)) }}
{%- elif g.current_user and event.actor_id == g.current_user.id -%}
  {{ _('You commented on a <strong>%(distance)s</strong> flight on the <strong>%(date)s</strong>.',
       distance=h.format_distance(event.flight.olc_classic_distance),
       date=h.format_date(event.flight.date_local)) }}
{%- else -%}
  {{ _('<strong>%(pilot)s</strong> commented on a <strong>%(distance)s</strong> flight on the <strong>%(date)s</strong>.',
       pilot=user_link(event.actor),
       distance=h.format_distance(event.flight.olc_classic_distance),
       date=h.format_date(event.flight.date_local)) }}
{%- endif %}
{%- endmacro %}


{% macro render_flight_event_text(event) -%}
{% if g.current_user and event.actor_id == g.current_user.id -%}
  {{ _('You uploaded a <strong>%(distance)s</strong> flight on the <strong>%(date)s</strong>.',
       distance=h.format_distance(event.flight.olc_classic_distance),
       date=h.format_date(event.flight.date_local)) }}
{%- else -%}
  {{ _('<strong>%(pilot)s</strong> uploaded a new <strong>%(distance)s</strong> flight on the <strong>%(date)s</strong>.',
       pilot=user_link(event.actor),
       distance=h.format_distance(event.flight.olc_classic_distance),
       date=h.format_date(event.flight.date_local)) }}
{%- endif %}
{%- endmacro %}


{% macro render_grouped_flights_event_text(event) -%}
{% if g.current_user and event.actor_id == g.current_user.id -%}
  {{ _('You uploaded <strong>%(num_flights)s</strong> new flights.',
       num_flights=event.subevents|count) }}
{%- else -%}
  {{ _('<strong>%(pilot)s</strong> uploaded <strong>%(num_flights)s</strong> new flights.',
       pilot=user_link(event.actor), num_flights=event.subevents|count) }}
{%- endif %}
{%- endmacro %}


{% macro render_follower_event_text(event) -%}
{% if g.current_user and event.user_id == g.current_user.id -%}
  {{ _('<strong>%(pilot)s</strong> is following you now.', pilot=user_link(event.actor)) }}
{%- elif g.current_user and event.actor_id == g.current_user.id -%}
  {{ _('You are following <strong>%(pilot)s</strong> now.', pilot=user_link(event.user)) }}
{%- else -%}
  {{ _('<strong>%(pilot)s</strong> is following <strong>%(pilot2)s</strong> now.', pilot=user_link(event.actor), pilot2=user_link(event.user)) }}
{%- endif %}
{%- endmacro %}


{% macro render_grouped_followers_event_text(event) -%}
{% if g.current_user and event.actor_id == g.current_user.id -%}
  {{ _('You are following <strong>%(num_pilots)s</strong> other pilots.', num_pilots=event.subevents|count) }}
{%- else -%}
  {{ _('<strong>%(pilot)s</strong> is following <strong>%(num_pilots)s</strong> other pilots.', pilot=user_link(event.actor), num_pilots=event.subevents|count) }}
{%- endif %}
{%- endmacro %}


{% macro _render_show_button(link) -%}
<a href="{{ link }}" class="btn btn-mini">{{ _('Show') }}</a>
{%- endmacro %}


{% macro event_link(event) -%}
{% if event.grouped -%}
  {% if event.type == types.FLIGHT -%}
    {{ url_for('flights.pilot', id=event.actor_id) }}
  {%- endif %}
{%- else %}
  {% if event.type == types.FLIGHT_COMMENT -%}
    {{ url_for('flight.index', flight_id=event.flight_id) }}
  {%- elif event.type == types.FLIGHT %}
    {{ url_for('flight.index', flight_id=event.flight_id) }}
  {%- elif event.type == types.FOLLOWER %}
    {{ url_for('user.index', user_id=event.user_id) }}
  {%- endif %}
{%- endif %}
{%- endmacro %}